### ISSUE TITLE
Not seeing any entities

### ISSUE THREAD

**Issue by FlamingMoose** [Thomas55555/husqvarna_automower#108]
After installing with Hacs and installing integration I can't see any entities.
It looks like the integration is installed ok but see this error in log
`2021-10-11 14:47:39 ERROR (MainThread) [custom_components.husqvarna_automower] Unexpected error fetching husqvarna_automower data: local variable 'result' referenced before assignment
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 187, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/husqvarna_automower/__init__.py", line 125, in _async_update_data
    await self.async_validate_token()
  File "/config/custom_components/husqvarna_automower/__init__.py", line 171, in async_validate_token
    await self.token_valid.async_validate_access_token()
  File "/usr/local/lib/python3.9/site-packages/aioautomower/__init__.py", line 142, in async_validate_access_token
    result["status"] = resp.status
UnboundLocalError: local variable 'result' referenced before assignment
2021-10-11 14:47:39 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up husqvarna_automower platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/device_tracker.py", line 19, in async_setup_entry
    for idx, ent in enumerate(coordinator.data["data"])
TypeError: 'NoneType' object is not subscriptable
2021-10-11 14:47:39 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up husqvarna_automower platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/vacuum.py", line 49, in async_setup_entry
    for idx, ent in enumerate(coordinator.data["data"])
TypeError: 'NoneType' object is not subscriptable`

I have the application set up also with the authentication and connect api.
![2021-10-11 14_57_07-Window](https://user-images.githubusercontent.com/74401010/136793864-f234b084-da3b-4cf1-971a-ff5f61be0ee6.png)

**Comment by FlamingMoose** [comment]
Updated to new version 2021.10.0.
Now I can see my entities. Thank You
