### ISSUE TITLE
Login failure

### ISSUE THREAD

**Issue by joejulian** [Thomas55555/husqvarna_automower#25]
I logged in to the developer site, created my application, added the connections, and got my API key (obfuscated).
![image](https://user-images.githubusercontent.com/952828/110374750-e891e780-8005-11eb-9589-ee81022e8acc.png)

When attempting to add the integration, I fill out the authentication form but it returns to a blank form. The following error is logged.
```
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:18:53 DEBUG (MainThread) [custom_components.husqvarna_automower.config_flow] Show the setup form to the user.
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 DEBUG (MainThread) [custom_components.husqvarna_automower.config_flow] Trying to connect to Husqvarna
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 DEBUG (MainThread) [husqvarna_automower] result: 400
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 DEBUG (MainThread) [husqvarna_automower] resp.status: 400
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 DEBUG (MainThread) [custom_components.husqvarna_automower.config_flow] Access token raw: 400
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 ERROR (MainThread) [custom_components.husqvarna_automower.config_flow] Unexpected exception
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: Traceback (most recent call last):
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]:   File "/config/custom_components/husqvarna_automower/config_flow.py", line 51, in async_step_user
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]:     await try_connection(
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]:   File "/config/custom_components/husqvarna_automower/config_flow.py", line 82, in try_connection
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]:     if "access_token" in access_token_raw:
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: TypeError: argument of type 'int' is not iterable
homeassistant/home-assistant-d8f49d8b8-xhg2p[home-assistant]: 2021-03-08 20:19:13 DEBUG (MainThread) [custom_components.husqvarna_automower.config_flow] Show the setup form to the user.
```
Using yesterday's release: `2021.3.2`

**Comment by Thomas55555** [comment]
This normally only happens, when there are wrong information in the credentials. Please check username, password and the api-key and try again.
Sorry, that's the only idea I have.

**Comment by joejulian** [comment]
It's the exact same credentials used for accessing the developer site, copy/pasted from keepass. I wonder if it could be an url encoding issue with the password.

**Comment by joejulian** [comment]
https://github.com/Thomas55555/husqvarna_automower_py/pull/10

**Comment by Thomas55555** [comment]
Thank you for contributing

**Comment by joejulian** [comment]
Always happy to help when I'm able. :)
