### ISSUE TITLE
Integration not showing mower status, keeps at paused.

### ISSUE THREAD

**Issue by frank8the9tank** [Thomas55555/husqvarna_automower#262]
**Prerequirements**
[yes] I have connected my mower(s) to the Automower Connect App
[yes] I have connected my Husqvanra developers account to the Authentication API
[yes] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Integration not showing the satus of the mower, keeps at paused,
But infact, through the app, the mower is mowing fine.
2 days ago the integration was working fine.
The husqvarana app is still working fine.

**Expected behavior**
couled this be that husqvarna working on the API? AIM introduction?

**Screenshots**

**Additional context**
From the HA log:
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/husqvarna_automower/__init__.py:140
Integration: Husqvarna Automower (documentation, issues)
First occurred: 12:48:32 (1 occurrences)
Last logged: 12:48:32

Error unloading entry Automower for husqvarna_automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 478, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/husqvarna_automower/__init__.py", line 140, in async_unload_entry
    await session.close()
  File "/usr/local/lib/python3.9/site-packages/aioautomower/session.py", line 150, in close
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.9/site-packages/aioautomower/session.py", line 336, in _rest_task
    self.data = await self.get_status()
  File "/usr/local/lib/python3.9/site-packages/aioautomower/session.py", line 165, in get_status
    return await d.async_mower_state()
  File "/usr/local/lib/python3.9/site-packages/aioautomower/rest.py", line 167, in async_mower_state
    async with session.get(MOWER_API_BASE_URL) as resp:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 913, in start
    self._continue = None
  File "/usr/local/lib/python3.9/site-packages/aiohttp/helpers.py", line 721, in __exit__
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError
`

**Comment by Thomas55555** [comment]
It looks like you have tried to unload the integration and there an error occurred.
Can you try to remove and add the integration again?

**Comment by frank8the9tank** [comment]
There where some bumps on the way, A update in the app, (AIM tech) and a firmware update.
But i have removed the integration, restarted HA en added it again (in 1 attempt, so no retries, etc)
Lets see if its stays online for longer than ~24hours.

**Comment by frank8the9tank** [comment]
Its already down again, so no communication with the mower.
Dumb question maybe, can you use the app and api connection at the same time?
(i look in the app where the mower is located)
I don't see anything in the log.

what can i do to help you solve this?
Do you need be to enable any logging, (if yes, please tell where and how)

**Comment by frank8the9tank** [comment]
just tried to enable additonal entities for this integration that resulted in:

![afbeelding](https://user-images.githubusercontent.com/84384888/178245587-4a24f98c-f10a-462d-844d-c767fca22537.png)

and the log shows:
`This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/husqvarna_automower/__init__.py:107
Integration: Husqvarna Automower (documentation, issues)
First occurred: 12:26:46 (1 occurrences)
Last logged: 12:26:46

Error unloading entry Automower for husqvarna_automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 492, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/husqvarna_automower/__init__.py", line 107, in async_unload_entry
    await session.close()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 150, in close
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 335, in _rest_task
    self.data = await self.get_status()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 165, in get_status
    return await d.async_mower_state()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/rest.py", line 179, in async_mower_state
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 500, message='Internal Server Error', url=URL('https://api.amc.husqvarna.dev/v1/mowers/')
`

**Comment by Thomas55555** [comment]
> : 500, message='Internal

As the logs say, it's an error 500. Normally the server is responsible for this error and not the client. So it looks like it's not a problem of the integration.

**Comment by frank8the9tank** [comment]
i've no longer seen this problem, so i'm closing it for now.
