### ISSUE TITLE
Camera Throwing Error

### ISSUE THREAD

**Issue by slegs** [Thomas55555/husqvarna_automower#284]
**Prerequirements**
[X ] I have connected my mower(s) to the Automower Connect App
[ X] I have connected my Husqvanra developers account to the Authentication API
[ X] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
The log is showing an error when trying to generate the camera image. IT looks like the API is not supplying the GPS coordinates of the mower even though all is connected properly. Images are found and coordinates of map image are set in config (as I was having this error first until I resolved)

**Expected behavior**
Image should be shown

**Screenshots**

**Additional context**
```
2022-07-11 11:31:35 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback AutomowerCamera.__init__.<locals>.<lambda>({'data': [{'attributes': {'battery': {'batteryPercent': 34}, 'calendar': {'tasks': [{...}]}, 'cuttingHeight': 2, 'headlight': {'mode': 'EVENING_ONLY'}, ...}, 'id': '36a6d9f9-9c5...-4819f93e62ab', 'type': 'mower'}], 'status': 200}) at /config/custom_components/husqvarna_automower/camera.py:68
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/husqvarna_automower/camera.py", line 68, in <lambda>
    lambda data: self._generate_image(data), schedule_immediately=True
  File "/config/custom_components/husqvarna_automower/camera.py", line 129, in _generate_image
    x1, y1 = self._scale_to_img(location, (map_image.size[0], map_image.size[1]))
  File "/config/custom_components/husqvarna_automower/camera.py", line 190, in _scale_to_img
    y = ((lat_lon[0] - old[0]) * (new[1] - new[0]) / (old[1] - old[0])) + new[0]
ZeroDivisionError: float division by zero
2022-07-11 11:31:35 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback AutomowerCamera.__init__.<locals>.<lambda>({'data': [{'attributes': {'battery': {'batteryPercent': 34}, 'calendar': {'tasks': [{...}]}, 'cuttingHeight': 2, 'headlight': {'mode': 'EVENING_ONLY'}, ...}, 'id': '36a6d9f9-9c5...-4819f93e62ab', 'type': 'mower'}], 'status': 200}) at /config/custom_components/husqvarna_automower/camera.py:68
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/config/custom_components/husqvarna_automower/camera.py", line 68, in <lambda>
    lambda data: self._generate_image(data), schedule_immediately=True
  File "/config/custom_components/husqvarna_automower/camera.py", line 129, in _generate_image
    x1, y1 = self._scale_to_img(location, (map_image.size[0], map_image.size[1]))
  File "/config/custom_components/husqvarna_automower/camera.py", line 190, in _scale_to_img
    y = ((lat_lon[0] - old[0]) * (new[1] - new[0]) / (old[1] - old[0])) + new[0]
ZeroDivisionError: float division by zero
```

**Comment by slegs** [comment]
Im on code from yesterday and Hass 2022.7.2

**Comment by Thomas55555** [comment]
@prairiesnpr: Can you have a look at this?

**Comment by prairiesnpr** [comment]
A few questions
what model is the mower? 
Does the device_tracker show a valid position?
Is the error present if the camera is disable in the configuration?

Also, if your comfortable sharing, I'd like to see the current camera configuration.  I can add a try/except block for that error and just disable the camera and log the error as a stop gap.

**Comment by slegs** [comment]
Hi there and thanks for the quick response

Its a Husqvarna 430x.
Device tracker shows a position but its not updating.
Error disappears when camera disabled.
See attached for images showing config 

thanks 
Paul

![Entities](https://user-images.githubusercontent.com/6764986/178356415-7c282fa5-9c48-4e17-927c-11994d100009.png)
![Device Tracker](https://user-images.githubusercontent.com/6764986/178356421-d8b00cff-22d0-4585-965a-74e480a4fc3d.png)
![Camera Settings](https://user-images.githubusercontent.com/6764986/178356424-d3b9757d-5317-4b9c-bf25-3b490d959ca9.png)

**Comment by slegs** [comment]
Ahh I see it now :) pasted lat and longitude values incorrectly. Let me check

**Comment by slegs** [comment]
Yes its working now!

Just need to get the coordinates right on my image
