### ISSUE TITLE
crash during authentication

### ISSUE THREAD

**Issue by ajhuitsing** [Thomas55555/husqvarna_automower#296]
(horrible and totally user-unfriendly) oauth authentication seems to be broken:

husqvarna_automower version = 2022.7.1
homeassistant version = 2022.7.3

2022-07-12 12:18:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 168, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 303, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 169, in async_resolve_external_data
    return await self._token_request(
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(

**Comment by Thomas55555** [comment]
(uncomplete and developer-unfriendly) issue can't be solved without more information:

- log ends at the most interessting part: `raise ClientResponseError(`
- in which case this happend?

**Comment by ajhuitsing** [comment]
@Thomas55555 : sorry for my sarcastic remark... all my user experiences involving o-auth2 are terrible... so it's not a complain about this add-on, or to you as a developer: I'm grateful that guys like you take the time to develop this at all!
It's merely about my horrible oauth2 user experiences.

**in which case this happend?**
this happened when trying to add our mower to home-assistant. It worked fine before (by providing the user & password credentials), but after update to latest home-assistant (2022.7.1) it didn't work anymore: then I updated your add-on to (2022.7.3) 

by the way: first I didn't change the 'redirect URL' on Husqvarna's side.. this resulted in a endless UI dialog sequence : I had to click OK, was directed to Husqvarna, provided my username & password, came back to home-assistant.. something went wrong... but never got the chance to change anything 

After I removed the application credentials in home assistant I could retry stuff. Even after I had removed the addon, and reinstalled the addon the application credentials were stored inside home-assistant.. this is unclear to me as a user.

** log ends at the most interessting part: raise ClientResponseError(**

here is the log again, including the last line:

2022-07-12 12:18:02 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 79, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 168, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 95, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 277, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 359, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 303, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 169, in async_resolve_external_data
    return await self._token_request(
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.authentication.husqvarnagroup.dev/v1/oauth2/token')

**Comment by icvdok** [comment]
Hello, not sure if it's the same issue but after the last update of the integration I've got this:
![Screenshot 2022-07-12 173743](https://user-images.githubusercontent.com/16425590/178531855-7d03f61f-18a3-4292-a5a6-20db628819d0.jpg)
 
Any help is really appreciated.

Note:
Auth key already created on Husqvarna dev site.
Integration version 2022.7.1
Home Assistant 2022.7.3

Thanks

**Comment by trickiegt** [comment]
Yeah, I filled in the wrong info and now its stuck in this loop... I cant seem to delete the integration and reload it.... just goes back to that error page every time now

**Comment by Thomas55555** [comment]
Just to be sure, no one is doing it wrong. I made I video about how to add the integration

https://user-images.githubusercontent.com/59625598/178572694-73986b4d-de13-4950-a774-be99da21defa.mp4

**Comment by adandl** [comment]
> @[trickiegt](https://github.com/trickiegt)
> 
> Better delete it in the UI: https://my.home-assistant.io/redirect/application_credentials/

that fixed it for me - thank you!

**Comment by nicolap75** [comment]
Hi, sorry, but what is the URL that should be put in the husqvarna site under redirect?

I receive that message:

> _Invalid client: `redirect_uri` does not match client value_

thx
N.

**Comment by nicolap75** [comment]
> Just to be sure, no one is doing it wrong. I made I video about how to add the integration
> 
>  simplescreenrecorder.mp4

I don't see the video, possibile?

THx
N.

**Comment by mulcmu** [comment]
Video didn't open in browser for me.  Here is URL to download directly.

`https://user-images.githubusercontent.com/59625598/178572694-73986b4d-de13-4950-a774-be99da21defa.mp4`

**Comment by ajhuitsing** [comment]
followed Thomas's video and now it connects.
most important missing thing was the matching string inside 'Description'.. which seems to need to match with the one entered during the 'link account' dialog.

still: a bit vague how to connect this.. but after fumbling around it now connects.

thank you Thomas!

**Comment by mulcmu** [comment]
@nicolap75 I recall getting the 
>Invalid client: *redirect_uri* does not match client value

error because I had an extra space at the end from when I selected the url to copy it.

**Comment by icvdok** [comment]
Fixed also on my side :-), many thanks Thomas for the video and the support.

**Comment by Thomas55555** [comment]
> 



> followed Thomas's video and now it connects. most important missing thing was the matching string inside 'Description'.. which seems to need to match with the one entered during the 'link account' dialog.
> 
> still: a bit vague how to connect this.. but after fumbling around it now connects.
> 
> thank you Thomas!

The string inside the description was just for copy and paste later. Normally I don't do that and it stills works.

**Comment by ajhuitsing** [comment]
and here we are again, a couple months later I've replaced the mosquitto settings, and now this integration is not working for me anymore... it's the same problem as before.

@Thomas: could you please re-post your video (it can't be opened anymore) ? somehow it contains the magic way how to use oauth2

the way I seem to use the UI results in the same 'oauth2' failure as before.


Consider using debug logging and log_response for further investigation.
2022-11-21 20:42:35.046 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 222, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 82, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 171, in get
    return await super().get(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 96, in get
    result = await self._flow_mgr.async_configure(flow_id)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 280, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 303, in async_step_creation
    token = await self.flow_impl.async_resolve_external_data(self.external_data)
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 169, in async_resolve_external_data
    return await self._token_request(
  File "/usr/src/homeassistant/homeassistant/helpers/config_entry_oauth2_flow.py", line 205, in _token_request
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.authentication.husqvarnagroup.dev/v1/oauth2/token')
