### ISSUE TITLE
Token error

### ISSUE THREAD

**Issue by schimi42** [Thomas55555/husqvarna_automower#3]
When sending any command to the automower I'm getting the error below. Data from the automower is shown correctly in Home Assistant so the connection to the Husqvarna service works.  

Logger: homeassistant.components.websocket_api.http.connection.139712531677248
Source: custom_components/husqvarna_automower/vacuum.py:137 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 13:34:14 (2 occurrences) 
Last logged: 13:39:02

'token'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 137, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1315, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1350, in _execute_service
    await handler.func(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 459, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 655, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 490, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 372, in async_pause
    await self.hass.async_add_executor_job(self.pause)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/husqvarna_automower/vacuum.py", line 137, in pause
    self.access_token = self.coordinator.data['data'][0]['token']['access_token']
KeyError: 'token'

**Comment by Thomas55555** [comment]
Should now work again. Please test with the new code.

**Comment by schimi42** [comment]
Thanks for the quick response! Works great now!
