### ISSUE TITLE
Problem with the istallation

### ISSUE THREAD

**Issue by dowermyr** [Thomas55555/husqvarna_automower#313]
**Prerequirements**
[x ] I have connected my mower(s) to the Automower Connect App
[ x] I have connected my Husqvanra developers account to the Authentication API
[x ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When installing the Integration, it prompts me to be ready with the API credentials. When I hit OK, nothing happens.

**Expected behavior**
I expect that there should be a new window, asking for the token etc

**Screenshots**

**Additional context**

**Comment by dowermyr** [comment]
Here is the log when I am trying to install:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 309, in handle_integration_list
    "integrations": {
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 310, in <dictcomp>
    domain: await _async_integration_config(hass, domain) for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 293, in _async_integration_config
    placeholders = await platform.async_get_description_placeholders(hass)
  File "/config/custom_components/husqvarna_automower/application_credentials.py", line 21, in async_get_description_placeholders
    "redirect_uri": get_url(hass),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
