### ISSUE TITLE
Automower cutting height entity doesn't work on my install

### ISSUE THREAD

**Issue by plasterer41** [Thomas55555/husqvarna_automower#317]
I have the 435x that allows the cutting height adjustment via the mobile app. The entity is showing up ok in Home Assistant but I get an error when I try to change the entity value.
Anyone else experience this or have a fix?

**Comment by Thomas55555** [comment]
What error?

**Comment by Thomas55555** [comment]
Ah, I think I got it. Can you change line 89 of the number.py from
```                "attributes": {"cuttingHeight": value},```
to:
```                "attributes": {"cuttingHeight": int(value)},```

reboot and test it again?

**Comment by plasterer41** [comment]
no joy with that either. Here is a pic of the error message...
![IMG](https://user-images.githubusercontent.com/47918336/179820364-b9bf1aa8-29f9-4298-9f84-c3003eb1d2ae.jpg)
.

**Comment by Thomas55555** [comment]
Can you have a look in your logfile? The should be something like this:
```
2022-07-19 18:18:05.758 DEBUG (MainThread) [aioautomower.rest] Mower Action URL: https://api.amc.husqvarna.dev/v1/mowers/b2bc3443-b31a-4c7f-834e-d6e408c53f1b/settings
2022-07-19 18:18:05.759 DEBUG (MainThread) [aioautomower.rest] Sent payload: {"data": {"type": "settings", "attributes": {"cuttingHeight": 5}}}
2022-07-19 18:18:05.759 DEBUG (MainThread) [aioautomower.rest] Resp status mower command: 202
2022-07-19 18:18:05.830 DEBUG (MainThread) [aioautomower.session] Received TEXT
```
and paste it here?

**Comment by plasterer41** [comment]
2022-07-19 19:25:25 DEBUG (MainThread) [aioautomower.rest] Mower Action URL: https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings
2022-07-19 19:25:25 DEBUG (MainThread) [aioautomower.rest] Sent payload: {"data": {"type": "settings", "attributes": {"cuttingHeight": 7}}}
2022-07-19 19:25:25 DEBUG (MainThread) [aioautomower.rest] Resp status mower command: 400
2022-07-19 19:25:25 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140596550574496] 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings')
Traceback (most recent call last):
  File "/config/custom_components/husqvarna_automower/number.py", line 94, in async_set_native_value
    await self.session.action(self.mower_id, payload, command_type)
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 180, in action
    return await a.async_mower_command()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/rest.py", line 232, in async_mower_command
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1004, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 193, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1713, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1750, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 680, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 930, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 717, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 102, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/husqvarna_automower/number.py", line 96, in async_set_native_value
    raise UpdateFailed(exception) from exception
homeassistant.helpers.update_coordinator.UpdateFailed: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings')
2022-07-19 19:25:28 ERROR (SyncWorker_19) [openwebif.api] There was a connection error calling http://192.168.5.85:80/api/statusinfo Please check the network connection to the Enigma2 box is ok and enable debug logging in Enigma2 if required. Error: HTTPConnectionPool(host='192.168.5.85', port=80): Max retries exceeded with url: /api/statusinfo (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fdf0009ce20>: Failed to establish a new connection: [Errno 113] Host is unreachable'))

**Comment by Thomas55555** [comment]
do other commands work, like changing the headlight mode?

**Comment by plasterer41** [comment]
Yes, takes a few seconds but all working except cutting height

**Comment by plasterer41** [comment]
the command ran ok but nothing happened. Here's the log for it....

2022-07-19 19:48:54 DEBUG (MainThread) [aioautomower.rest] Mower Action URL: https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings
2022-07-19 19:48:54 DEBUG (MainThread) [aioautomower.rest] Sent payload: {"data": {"type": "settings", "attributes": {"cuttingHeight": 5}}}
2022-07-19 19:48:54 DEBUG (MainThread) [aioautomower.rest] Resp status mower command: 400
2022-07-19 19:48:54 ERROR (MainThread) [custom_components.husqvarna_automower.vacuum] Command couldn't be sent to the command que: 400, message='Bad Request', url=URL('https://api.amc.husqvarna.dev/v1/mowers/8bd3aa3e-2487-45b6-a764-1b4c20d30643/settings')

**Comment by plasterer41** [comment]
When I look at the 435x cutting height history, it is showing the cutting height but it just won't send any changes for some reason.

**Comment by Thomas55555** [comment]
Then I have no idea. Because I don't have a mower supporting this. Can only stimulate it.
Maybe other users can help.

**Comment by plasterer41** [comment]
no problem. Thanks for trying and thanks for a great integration nonetheless :-)

**Comment by OEHC** [comment]
I have a 415X and get the same error as @plasterer41 when adjusting the cutting height. I've never tried changing it from HA before, so I cannot tell if the problem has been there all along. Cutting height is reported correctly for me as well.

**Comment by OEHC** [comment]
I am able to change headlight mode through the API:
```
curl -X 'POST' \
  'https://api.amc.husqvarna.dev/v1/mowers/20ea32ed-8e38-461b-8b0e-b5a48026dd19/settings' \
  -H 'accept: application/vnd.api+json' \
  -H 'X-Api-Key: REDACTED' \
  -H 'Authorization: Bearer REDACTED' \
  -H 'Authorization-Provider: husqvarna' \
  -H 'Content-Type: application/vnd.api+json' \
  -d '{
  "data": {
    "type": "settings",
    "attributes": {
      "headlight": {
        "mode": "ALWAYS_ON"
      }
    }
  }
}'
{"data":[{"type":"HeadlightSettings","id":"bba050a0-d1b1-4c69-b7f7-401e60a37f3e","attributes":null}]}
```

But changing cutting height gives this error:
```
curl -X 'POST' \
  'https://api.amc.husqvarna.dev/v1/mowers/20ea32ed-8e38-461b-8b0e-b5a48026dd19/settings' \
  -H 'accept: application/vnd.api+json' \
  -H 'X-Api-Key: REDACTED' \
  -H 'Authorization: Bearer REDACTED' \
  -H 'Authorization-Provider: husqvarna' \
  -H 'Content-Type: application/vnd.api+json' \
  -d '{
  "data": {
    "type": "settings",
    "attributes": {
      "cuttingHeight": 6
    }
  }
}'
{"errors":[{"id":"6bb56aef-e9f9-4346-a651-280356149d75","status":"400","code":"illegal.argument","title":"Illegal argument","detail":"This mower use missions and can not be updated by this endpoint"}]}
```

**Comment by plasterer41** [comment]
Not just me then. Reassuring that it may not be something I’ve done or haven’t done. Thanks for advising @OEHC

**Comment by Nordicfastware** [comment]
Hello, i have the 415x and have the same problem as reported by @plasterer41.

**Comment by Thomas55555** [comment]
I found another repository. They write it's not working for certain models:
https://github.com/ice987987/ioBroker.husqvarna-automower#license

**Comment by Thomas55555** [comment]
That's the explanation for missions: 
ice987987/ioBroker.husqvarna-automower#23
