### ISSUE TITLE
Can't enter credentials

### ISSUE THREAD

**Issue by Fizzyflaskan88** [Thomas55555/husqvarna_automower#321]
Starting to get connection issues after updating the home assistant (meaning I had everything up and running).
Since it had troubles reconnecting, and I could not do anything with the configuration of the integration I removed it and tried to add it again. Now I get prompted with this:

![prompt](https://user-images.githubusercontent.com/42077913/180399747-722e3dcd-af64-44d6-9b39-4b10aeb27962.png)

After pressing OK nothing happens.
In the log I can see this issue:

2022-07-22 10:29:59 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [548078333728] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 309, in handle_integration_list
    "integrations": {
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 310, in <dictcomp>
    domain: await _async_integration_config(hass, domain) for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 293, in _async_integration_config
    placeholders = await platform.async_get_description_placeholders(hass)
  File "/config/custom_components/husqvarna_automower/application_credentials.py", line 21, in async_get_description_placeholders
    "redirect_uri": get_url(hass),
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 201, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError

Which seems to be an error that it can't find my credentials , which I havn't got promted for yet...

**Comment by Thomas55555** [comment]
It seems like you the integration can't find your URL, where HomeAssistant can't be reached.
Have you configured your URL in HomeAssistant/Settings/System/Network?

**Comment by Fizzyflaskan88** [comment]
somehow that had been removed during some update. thanks for pointing me in correct direction!
