### ISSUE TITLE
Setting up application credentials fails when external url not set in settings

### ISSUE THREAD

**Issue by svenzik** [Thomas55555/husqvarna_automower#357]
Error happens during setup process described in README.md:
```
Add the integration to your home assistant installation and test the redirect feature by following below link: my_button
Acknowledge prompts to open link, install Husqvarna Automower integration.
Acknowledge prompt to setup application credentials. <-- here
```

The failure indicates that there is no config for external url and the get_url cannot guess it using websocket.

Solution:
User must go to page `Settings -> Network` and set the field `Internet` to actual external url.
Could you add this to your README.md.

Error from log:

ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140602298231552] Error handling message: Unknown error (unknown_error)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 330, in handle_integration_list
    "integrations": {
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 331, in <dictcomp>
    domain: await _async_integration_config(hass, domain) for domain in domains
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 314, in _async_integration_config
    placeholders = await platform.async_get_description_placeholders(hass)
  File "/config/custom_components/husqvarna_automower/application_credentials.py", line 22, in async_get_description_placeholders
    "redirect_uri": get_url(hass)
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError

**Comment by G-R-O** [comment]
I have "Use Home Assistant Cloud" set TRUE and it doesn't work, why?
