### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by Gloomyeye** [Thomas55555/husqvarna_automower#405]
**Prerequirements**
[  x ] I have connected my mower(s) to the Automower Connect App
[  x ] I have connected my Husqvanra developers account to the Authentication API
[  x ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**

Some sensors are not available with the newest version of home assistant 2023.4.0. An error occurs in the log.

These sensors are not working anymore:
sensor.gar_mower_husky_battery_level, sensor.gar_mower_husky_cutting_blade_usage_time, sensor.gar_mower_husky_cutting_time_percent, sensor.gar_mower_husky_next_start, sensor.gar_mower_husky_number_of_charging_cycles, sensor.gar_mower_husky_searching_time_percent, sensor.gar_mower_husky_total_charging_time, sensor.gar_mower_husky_total_running_time, sensor.gar_mower_husky_number_of_collisions, sensor.gar_mower_husky_problem

**Expected behavior**

No errors, all sensors available.

**Additional context**

```
Logger: homeassistant.components.sensor
Source: custom_components/husqvarna_automower/sensor.py:224
Integration: Sensor (documentation, issues) 
First occurred: 11:04:59 (1 occurrences) 
Last logged: 11:04:59

Error while setting up husqvarna_automower platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/sensor.py", line 247, in async_setup_entry
    description.value_fn(session.data["data"][idx]["attributes"])
  File "/config/custom_components/husqvarna_automower/sensor.py", line 224, in <lambda>
    value_fn=lambda data: get_problem(data).lower(),
AttributeError: 'NoneType' object has no attribute 'lower'

```

**Comment by Thomas55555** [comment]
Can you test if 2023.4.1b0 of husqvarna automower solves the problem?

**Comment by Gloomyeye** [comment]
Version 2023.4.1b0 looks way better. No errors in the log. The missing sensors are now available.
Thanks!

**Comment by Thomas55555** [comment]
They are deactivated by default. You have to activate them manually, if you
want

ebnerjoh ***@***.***> schrieb am Do., 6. Apr. 2023, 20:34:

**Comment by ebnerjoh** [comment]
Oh, yes....

Thanks! :-)
