### ISSUE TITLE
Missing Entities since upgrade to the latest version

### ISSUE THREAD

**Issue by ebnerjoh** [Thomas55555/husqvarna_automower#406]
Hi, with the older version .2 I had much more entities for my AutoMower. Since the upgrade most of them are gone. I have also removed the Integration and readded with a new authorization. Still the same.

Eg. all the statistics (e.g. mowing time, charging time, ...) are also gone.

**Comment by ebnerjoh** [comment]
In the logs I can see one error:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 293, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/sensor.py", line 247, in async_setup_entry
    description.value_fn(session.data["data"][idx]["attributes"])
  File "/config/custom_components/husqvarna_automower/sensor.py", line 224, in <lambda>
    value_fn=lambda data: get_problem(data).lower(),
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by Thomas55555** [comment]
Can you test if 2023.4.1b0 of husqvarna automower solves the problem?

**Comment by Thomas55555** [comment]
duplicate to #405 
Please report the result of your test in #405
