### ISSUE TITLE
Authentication stops working when enabling disabled entities

### ISSUE THREAD

**Issue by ebnerjoh** [Thomas55555/husqvarna_automower#411]
Hello,

I have the latest Home Assistant and Automower Integration installed.

It seems that the Token Authentication fails when I enable the disabled entities of the Integration. This is the error log.

```
2023-04-07 08:06:50.212 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [22587735212432] Connection closed by client
2023-04-07 08:07:08.478 INFO (MainThread) [homeassistant.config_entries] Reloading configuration entries because disabled_by changed in entity registry: 9961c6488644f2a438920a84f1835c74
2023-04-07 08:07:08.669 DEBUG (MainThread) [aioautomower.rest] Resp.status delete token: 400
2023-04-07 08:07:08.671 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for husqvarna_automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 539, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/husqvarna_automower/__init__.py", line 60, in async_unload_entry
    await session.close()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 141, in close
    await self.invalidate_token()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/session.py", line 193, in invalidate_token
    return await token.async_delete_access_token()
  File "/usr/local/lib/python3.10/site-packages/aioautomower/rest.py", line 136, in async_delete_access_token
    resp.raise_for_status()
  File "/usr/local/lib/python3.10/site-packages/aiohttp/client_reqrep.py", line 1005, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url=URL('https://api.authentication.husqvarnagroup.dev/v1/oauth2/revoke')
```
I also cannot remove the auth token as it alsways says that it is in use from Automower Integration. I can only then delete the integration and install it again.

Br,
Johannes

**Comment by Thomas55555** [comment]
Should be solved in 2023.4.2
Can you check?
