### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by chmeeedalf** [Thomas55555/husqvarna_automower#421]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
When following the link from the README, or trying through the "+ Add Integration" from the Home Assistant settings page, it appears to start, but immediately flashes away, not allowing me to do anything.  I see the following in my log:

```
2023-04-14 09:33:22.311 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [5211148336] Error handling message: Unknown error (unknown_error) **redacted_user** from **redacted_IP** (Mozilla/5.0 (X11; Linux ppc64le; rv:107.0) Gecko/20100101 Firefox/107.0)
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/application_credentials/__init__.py", line 330, in handle_integration_list
    "integrations": {
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/application_credentials/__init__.py", line 331, in <dictcomp>
    domain: await _async_integration_config(hass, domain) for domain in domains
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/components/application_credentials/__init__.py", line 314, in _async_integration_config
    placeholders = await platform.async_get_description_placeholders(hass)
  File "/home/hass/homeassistant/custom_components/husqvarna_automower/application_credentials.py", line 22, in async_get_description_placeholders
    "redirect_uri": get_url(hass),
  File "/srv/homeassistant/lib/python3.10/site-packages/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableError
```
I've tried from browsers running on Linux (Firefox), macOS (Brave and Safari), and Android (Samsung browser), as well as the Android Home-Assistant app.

**Expected behavior**
I expect a configuration window to pop up to add the API credentials.

**Screenshots**

**Additional context**
Running Home Assistant 2023.4.4 in a jail on FreeBSD

**Comment by Thomas55555** [comment]
Have you filled out the URL information in home assistant / system / network?
If not, please do so and try again

**Comment by chmeeedalf** [comment]
That was the problem, thanks!  I got confused when the "Network" page was blanked out.
