### ISSUE TITLE
Exception: `Could not parse date for dictionary value @ data['end']`

### ISSUE THREAD

**Issue by j-steve** [Thomas55555/husqvarna_automower#423]
**Prerequirements**
[x] I have connected my mower(s) to the Automower Connect App
[x] I have connected my Husqvanra developers account to the Authentication API
[x] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
Following exception occurs:
```
2023-04-16 01:58:13.266 ERROR (MainThread) [homeassistant] Error doing job: Exception in callback AutomowerEntity.async_added_to_hass.<locals>.<lambda>({'data': [{'attributes': {'battery': {'batteryPercent': 100}, 'calendar': {'tasks': [{...}]}, 'cuttingHeight': 1, 'headlight': {'mode': 'EVENING_AND_NIGHT'}, ...}, 'id': 'c6128267-c9d...-6552726aff09', 'type': 'mower'}]}) at /config/custom_components/husqvarna_automower/entity.py:49
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 351, in __post_init__
    CALENDAR_EVENT_SCHEMA(dataclasses.asdict(self, dict_factory=skip_none))
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 272, in __call__
    return self._compiled([], data)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 229, in _run
    return self._exec(self._compiled, value, path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 355, in _exec
    raise e if self.msg is None else AllInvalid(self.msg, path=path)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/validators.py", line 353, in _exec
    v = func(path, v)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 595, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python3.10/site-packages/voluptuous/schema_builder.py", line 433, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: Could not parse date for dictionary value @ data['end']
```
**Expected behavior**
(expect no error)

**Screenshots**

**Additional context**

**Comment by Thomas55555** [comment]
Duplicate to #393 
Is actually fixed in the current version. Which version do you use?
