### ISSUE TITLE
No vacuum entity after installing

### ISSUE THREAD

**Issue by mikje** [Thomas55555/husqvarna_automower#426]
**Prerequirements**
[x ] I have connected my mower(s) to the Automower Connect App
[x ] I have connected my Husqvanra developers account to the Authentication API
[x ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
After installing the integration and configure it, no new vacuum entity is created

**Expected behavior**
A new vacuum entity

**Screenshots**
![image](https://user-images.githubusercontent.com/12999690/233325803-505dd1ec-7c27-43a3-8247-e599eb3bbc93.png)
![image](https://user-images.githubusercontent.com/12999690/233325926-a2cc7046-532c-4815-8751-5cebe926916b.png)
![image](https://user-images.githubusercontent.com/12999690/233325974-fc0b3276-1b60-4b7a-b3de-42b236dc9149.png)
![image](https://user-images.githubusercontent.com/12999690/233326112-adb70a6a-ed82-444b-b731-2619d59564bf.png)

**Comment by borsti0** [comment]
Same problem here with Automower 435X AWD. All "Prerequirements" installed/executed. Did I miss something?

**Comment by hollie** [comment]
Hello,

This integration has been working great for me in the last year. 
I want to chime in that I am experiencing the same issue after updating HA, HACS and the plugin to the latest version.

The error I see in the logs:

```
home-assistant  | 2023-04-21 20:53:53.683 ERROR (MainThread) [aioautomower.rest] Response mower data: {'Message': 'User is not authorized to access this resource with an explicit deny'}
home-assistant  | 2023-04-21 20:53:53.693 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up husqvarna_automower platform for binary_sensor
home-assistant  | Traceback (most recent call last):
home-assistant  |   File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
home-assistant  |     await asyncio.shield(task)
home-assistant  |   File "/config/custom_components/husqvarna_automower/binary_sensor.py", line 26, in async_setup_entry
home-assistant  |     for idx, ent in enumerate(session.data["data"])
home-assistant  | KeyError: 'data'
```

and this repeats for:

```
Error while setting up husqvarna_automower platform for calendar
Error while setting up husqvarna_automower platform for device_tracker
Error while setting up husqvarna_automower platform for number
Error while setting up husqvarna_automower platform for select
Error while setting up husqvarna_automower platform for sensor
Error while setting up husqvarna_automower platform for vacuum
```

Kind regards,
 Lieven

**Comment by borsti0** [comment]
I get a different debug log entry:

```
2023-04-23 00:19:50.351 DEBUG (MainThread) [aioautomower.rest] Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [200 OK]>
<CIMultiDictProxy('Content-Type': 'application/vnd.api+json', 'Content-Length': '11', 'Connection': 'keep-alive', 'Date': 'Sat, 22 Apr 2023 22:19:50 GMT', 'x-amzn-RequestId': '1c0c8421-ee11-4b72-8add-85ac0e6398f6', 'x-amzn-Remapped-Content-Length': '11', 'x-amzn-Remapped-Connection': 'keep-alive', 'x-amz-apigw-id': 'DzONBFZjjoEFhrg=', 'x-amzn-Remapped-Date': 'Sat, 22 Apr 2023 22:19:50 GMT', 'X-Cache': 'Miss from cloudfront', 'Via': '1.1 f0aabb4cf746d4b45640e8d63e2aaf1c.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'VIE50-P1', 'X-Amz-Cf-Id': 'oy5AnkW0NcrDycoEvEG1erPj3o7n8gOiVXj2ikqSNMYWmraEKtoJqQ==')>

2023-04-23 00:19:50.352 DEBUG (MainThread) [aioautomower.rest] Result mower data: {'data': []}
2023-04-23 00:19:50.355 DEBUG (MainThread) [aioautomower.session] LE: False

```

The empty entry for "Result mover data" seems odd

**Comment by borsti0** [comment]
OK, after once again uninstalling the HACS Husqvarna integration (including the authentication) and reinstalling the integration all seems to be fine now.
I did NOT change anything at the Husqvarna-side so it is properly something at the HA side.
Besides installing the regular updates I only changed that I added the "my:"-Line to the configuration.yaml to handle the "My Home Assistant"-redirection ([https://www.home-assistant.io/integrations/my/](https://www.home-assistant.io/integrations/my/)). Following this documentation it should not have been necessary, but redirects did not work properly for my HA-implementation so I added this line anyway. I don't know if this change and/or the reinstallation of the integration did resolve my problem.

**Comment by hollie** [comment]
@borsti0 

Thanks for the hint. I had already tried removing the integration but I did not remove the credentials. After a complete removal of both the integration and the credentials everything is working again as expected. The mower was detected and we're up and running again!

I did not setup the 'My Home assistant' redirection.

**Comment by mikje** [comment]
Alas,  I several times remover both the integration and the credentials but it does not work here
________________________________
Van: Lieven Hollevoet ***@***.***>
Verzonden: maandag 24 april 2023 19:01
Aan: Thomas55555/husqvarna_automower ***@***.***>
CC: mikje ***@***.***>; Author ***@***.***>
Onderwerp: Re: [Thomas55555/husqvarna_automower] No vacuum entity after installing (Issue #426)


@borsti0<https://github.com/borsti0>

Thanks for the hint. I had already tried removing the integration but I did not remove the credentials. After a complete removal of both the integration and the credentials everything is working again as expected. The mower was detected and we're up and running again!

I did not setup the 'My Home assistant' redirection.

**Comment by hollie** [comment]
@mikje is there anything you can share from your logs that might help in troubleshooting?

**Comment by mikje** [comment]
Is there some way of log this thing more in detail?
________________________________
Van: Lieven Hollevoet ***@***.***>
Verzonden: dinsdag 25 april 2023 06:44
Aan: Thomas55555/husqvarna_automower ***@***.***>
CC: mikje ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Thomas55555/husqvarna_automower] No vacuum entity after installing (Issue #426)


@mikje<https://github.com/mikje> is there anything you can share from your logs that might help in troubleshooting?

**Comment by hollie** [comment]
The logs I got are straight from the HomeAssistant main logfile. I did not enable any specific more logging.

**Comment by mikje** [comment]
I dont see any logging regarding the husqvarna

[cid:22c11c03-4104-4e64-9e51-3174a6894a71]


________________________________
Van: Lieven Hollevoet ***@***.***>
Verzonden: dinsdag 25 april 2023 07:36
Aan: Thomas55555/husqvarna_automower ***@***.***>
CC: mikje ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Thomas55555/husqvarna_automower] No vacuum entity after installing (Issue #426)


The logs I got are straight from the HomeAssistant main logfile. I did not enable any specific more logging.

**Comment by hollie** [comment]
Hey @mikje,

hmm, strange. When connect to the Husqvarna developer account, both the authentication and automower connect API are visible in the application you defined?

![image](https://user-images.githubusercontent.com/697364/234679948-07cf6da9-2584-4931-88d0-37f1e288cba4.png)

Also to enable debug information in the log, please see [here](https://github.com/Thomas55555/husqvarna_automower/blob/main/README.md#debugging).

**Comment by mikje** [comment]
Yes they are , I dont have the my: in my config.yaml and the default_config shows that it cannot load some url
________________________________
Van: Lieven Hollevoet ***@***.***>
Verzonden: woensdag 26 april 2023 19:19
Aan: Thomas55555/husqvarna_automower ***@***.***>
CC: mikje ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Thomas55555/husqvarna_automower] No vacuum entity after installing (Issue #426)


Hey @mikje<https://github.com/mikje>,

hmm, strange. When connect to the Husqvarna developer account, both the authentication and automower connect API are visible in the application you defined?

[image]<https://user-images.githubusercontent.com/697364/234679948-07cf6da9-2584-4931-88d0-37f1e288cba4.png>

Also to enable debug information in the log, please see here<https://github.com/Thomas55555/husqvarna_automower/blob/main/README.md#debugging>.

**Comment by hollie** [comment]
> the default_config shows that it cannot load some url

So there is an entry in your logs? Can you be more specific?

**Comment by Thomas55555** [comment]
There is no attachment. But check, if you've set your external url? See #357

**Comment by mikje** [comment]
It is set
________________________________
Van: Thomas55555 ***@***.***>
Verzonden: vrijdag 28 april 2023 13:44
Aan: Thomas55555/husqvarna_automower ***@***.***>
CC: mikje ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [Thomas55555/husqvarna_automower] No vacuum entity after installing (Issue #426)


There is no attachment. But check, if you've set your external url? See #357<https://github.com/Thomas55555/husqvarna_automower/issues/357>

**Comment by slovdahl** [comment]
I suddenly started having the same issue 🤔 

During startup:

```
2023-06-10 13:32:32.484 ERROR (MainThread) [aioautomower.rest] Response mower data: {'Message': 'User is not authorized to access this resource with an explicit deny'}
2023-06-10 13:32:34.186 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up husqvarna_automower platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/binary_sensor.py", line 25, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
```

But in HA it looks like the integration successfully loaded, but all entities are unavailable. If I try to reload the integration, I get this in the log and the integration is left in a broken half-unloaded state:

```
2023-06-10 13:50:42.694 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry Robotgräsklippare for husqvarna_automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
    result = await component.async_unload_entry(hass, self)
  File "/config/custom_components/husqvarna_automower/__init__.py", line 92, in async_unload_entry
    await session.close()
AttributeError: 'AutomowerDataUpdateCoordinator' object has no attribute 'close'
```

**Comment by Thomas55555** [comment]
I've found the issue why reloading doesn't work. This is fixed in #487.
But no idea, where the other issue comes from.
Maybe you can try the newest version of this integration, which will be released in a few minutes.

**Comment by slovdahl** [comment]
I found this that sounds a bit similar: https://community.openhab.org/t/gardenaaccounthandler-error-403-forbidden-user-is-not-authorized-to-access-this-resource-with-an-explicit-deny/145685/12.

Could `aioautomower` handle this condition and raise an exception that would trigger a re-authentication in HA? 🤔

**Comment by slovdahl** [comment]
This is the debug log from startup:

```
2023-06-10 19:56:26.768 DEBUG (MainThread) [aioautomower.rest] Response mower data: <ClientResponse(https://api.amc.husqvarna.dev/v1/mowers/) [403 Forbidden]>
<CIMultiDictProxy('Content-Type': 'application/json', 'Content-Length': '82', 'Connection': 'keep-alive', 'Date': 'Sat, 10 Jun 2023 16:56:26 GMT', 'x-amzn-RequestId': 'xxx', 'x-amzn-ErrorType': 'AccessDeniedException', 'x-amz-apigw-id': 'GT-xOGnbDoEFrig=', 'X-Cache': 'Error from cloudfront', 'Via': '1.1 837bfbe95037e42cdc86bcbd263354ea.cloudfront.net (CloudFront)', 'X-Amz-Cf-Pop': 'HEL51-P2', 'X-Amz-Cf-Id': 'xxxx')>

2023-06-10 19:56:26.770 ERROR (MainThread) [aioautomower.rest] Response mower data: {'Message': 'User is not authorized to access this resource with an explicit deny'}
2023-06-10 19:56:26.789 DEBUG (MainThread) [custom_components.husqvarna_automower] Finished fetching husqvarna_automower data in 1.437 seconds (success: True)
2023-06-10 19:56:26.802 DEBUG (MainThread) [aioautomower.session] LE: False
2023-06-10 19:56:26.802 DEBUG (MainThread) [aioautomower.session] token_monitor_task sleeping for 15220.407933473587 sec
2023-06-10 19:56:27.331 DEBUG (MainThread) [aioautomower.session] Websocket (re)connected
2023-06-10 19:56:27.370 DEBUG (MainThread) [aioautomower.session] Websocket ready=True (id='xxxxxx')
2023-06-10 19:56:28.550 DEBUG (MainThread) [custom_components.husqvarna_automower.calendar] entry: <homeassistant.config_entries.ConfigEntry object at 0xffffb5106330>
2023-06-10 19:56:28.561 ERROR (MainThread) [homeassistant.components.binary_sensor] Error while setting up husqvarna_automower platform for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/binary_sensor.py", line 25, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
2023-06-10 19:56:28.568 ERROR (MainThread) [homeassistant.components.calendar] Error while setting up husqvarna_automower platform for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/calendar.py", line 34, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
2023-06-10 19:56:28.584 ERROR (MainThread) [homeassistant.components.device_tracker] Error while setting up husqvarna_automower platform for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/device_tracker.py", line 21, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"]):
KeyError: 'data'
2023-06-10 19:56:28.595 ERROR (MainThread) [homeassistant.components.number] Error while setting up husqvarna_automower platform for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/number.py", line 29, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
2023-06-10 19:56:28.601 ERROR (MainThread) [homeassistant.components.select] Error while setting up husqvarna_automower platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/select.py", line 25, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
2023-06-10 19:56:28.610 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up husqvarna_automower platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/sensor.py", line 260, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"]):
KeyError: 'data'
2023-06-10 19:56:28.617 ERROR (MainThread) [homeassistant.components.vacuum] Error while setting up husqvarna_automower platform for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/husqvarna_automower/vacuum.py", line 51, in async_setup_entry
    for idx, ent in enumerate(coordinator.session.data["data"])
KeyError: 'data'
```

**Comment by mikje** [comment]
it is still not adding new entities, so not working

**Comment by slovdahl** [comment]
I deleted the integration and re-added, and as expected, now it works again. So somehow the authenticait

**Comment by Thomas55555** [comment]
> I found this that sounds a bit similar: https://community.openhab.org/t/gardenaaccounthandler-error-403-forbidden-user-is-not-authorized-to-access-this-resource-with-an-explicit-deny/145685/12.
> 
> Could `aioautomower` handle this condition and raise an exception that would trigger a re-authentication in HA? 🤔 https://github.com/Thomas55555/aioautomower/blob/7104d8e15ee59ad2e6cdc12f8b671e556a2b77d3/aioautomower/rest.py#L174

Yes, we could trigger on a 403 error re-authentication. But then the integration would just try to get a new token with the existing credentials. As far as I understood, you have to renew the API key and the client secret as well?

**Comment by slovdahl** [comment]
Yeah, that might be 🤔 Can we notify the user about that too? For example do one or a few re-authentications, and if they fail, ask the user to renew the credentials. Maybe a bit intrusive..

**Comment by Din-BH** [comment]
Thanks for getting me on the right thread @Thomas55555 . I just checked - there is nothing wrong with the credentials I have on the Husqvarna DEV site. I can authorize and use the Connect API with postman with the same client secrets. As you anticipated, reauthorizing did not help.

**Comment by Din-BH** [comment]
Ok, so somehow the authorization key has been garbled - without any action on my side?? I re-added the secrets to the section, and the integration started working again without any other changes. Only issue left is that the old credentials are still there, and cannot be removed since HA says the integration is using them.
