### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lower'

### ISSUE THREAD

**Issue by tomdevos2401** [Thomas55555/husqvarna_automower#430]
**Prerequirements**
[ ] I have connected my mower(s) to the Automower Connect App
[ ] I have connected my Husqvanra developers account to the Authentication API
[ ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
2023-04-22 10:32:44.814 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up husqvarna_automower platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
await asyncio.shield(task)
File "/config/custom_components/husqvarna_automower/sensor.py", line 249, in async_setup_entry
description.value_fn(session.data["data"][idx]["attributes"])
File "/config/custom_components/husqvarna_automower/sensor.py", line 214, in <lambda>
value_fn=lambda data: data["mower"]["mode"].lower(),
AttributeError: 'NoneType' object has no attribute 'lower'

**Expected behavior**
the device remains on Unavailable

**Comment by Thomas55555** [comment]
I have the same problem since this morning. There are coming None values from the API. Seems to be a problem in the server side.

**Comment by kleinerhobbit** [comment]
Thanks for sharing.
I have been experiencing the same problem since this morning.
In this case, i will wait until its fixed from server side.
Cheers.

**Comment by tomdevos2401** [comment]
thanks @Thomas55555 for sharing. 
keep up the good work on this integration.

**Comment by tomdevos2401** [comment]
it seems to be working again.

**Comment by kleinerhobbit** [comment]
Also here.
After restarting homeassistant today morning.
Everything is back online.
👌
