### ISSUE TITLE
Camera image disappears after some time in 2023.5.1b8

### ISSUE THREAD

**Issue by Din-BH** [Thomas55555/husqvarna_automower#470]
Upgraded from 5.0 release to 5.1beta8. Everything worked fine for some time, but now the camera sensor does not work - rest is OK. The HA instance was started at 18:31 - error condition seems to have started at 22:23. Mower schedule ends at 22 at the moment. Rebooting fixed the issue for now, not sure how frequent this error could occur. Log of where this seemingly happened shows the following;

2023-05-27 22:23:36.205 DEBUG (MainThread) [aioautomower.session] Refresh access token
2023-05-27 22:23:36.610 DEBUG (MainThread) [aioautomower.rest] Resp.status refresh token: {'access_token': 'xxx', 'scope': 'iam:read amc:api', 'expires_in': 86399, 'refresh_token': 'xxx', 'provider': 'husqvarna', 'user_id': 'xxx', 'token_type': 'Bearer'}
2023-05-27 22:23:36.616 DEBUG (MainThread) [aioautomower.session] token_monitor_task sleeping for 82798.9955060482 sec
2023-05-27 22:23:36.621 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for camera
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 543, in async_unload
result = await component.async_unload_entry(hass, self)
File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 426, in async_unload_entry
return await component.async_unload_entry(entry)
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 196, in async_unload_entry
await platform.async_reset()
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 745, in async_reset
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 867, in async_remove
await self.async_will_remove_from_hass()
File "/config/custom_components/husqvarna_automower/entity.py", line 58, in async_will_remove_from_hass
self.session.unregister_data_callback(lambda _: self.async_write_ha_state())
AttributeError: 'AutomowerCamera' object has no attribute 'session'

Also seeing a lot of these (below); approximately every 5 minutes apart, where the ws updates seem to stop. Then in between data again seems to be flowing.. Not sure if related.
2023-05-28 00:04:37.984 DEBUG (MainThread) [aioautomower.session] Age in sec: 4460
2023-05-28 00:04:37.987 DEBUG (MainThread) [aioautomower.session] No ws updates anymore and mower connected, ws probably down or mower shortly before disconnecting

**Comment by Thomas55555** [comment]
Normally I don't use this function. I've activated it an hour ago. But no errors so far...

**Comment by Din-BH** [comment]
Happened again yesterday. Worked the day, stopped working after 'daily limit' reached. So could be related to mower being outside schedule somehow? But that might still be a coincidence - resetted the HA a few times during the day yesterday. At least it did not recover automatically, so since reloading the extension is not available, restarting HA seems only remedy for now.

**Comment by Thomas55555** [comment]
Nevertheless I've found an issue in the camera. I've fixed it in version 2025.5.1b9
Is this version working for you?

**Comment by Din-BH** [comment]
No, unfortunately same issue remains.

**Comment by prairiesnpr** [comment]
Are you still seeing the same error in the logs?  The data update coordinator broke a few things.

**Comment by Din-BH** [comment]
Yes  same error.

**Comment by prairiesnpr** [comment]
This may be related to a bug in the entity itself, if you reload the integration, does it reload or tell you to to restart home assistant?

**Comment by Thomas55555** [comment]
You're right. I think I missed that.

**Comment by Din-BH** [comment]
Seems that did the trick. 5.1 has been up until now. Thanks to all helping in!
