### ISSUE TITLE
2023.6.1b0 KeyError: 'enable_camera'

### ISSUE THREAD

**Issue by robinostlund** [Thomas55555/husqvarna_automower#494]
Got this in my logs when i updated to 2023.6.1b0:
```
2023-06-20 14:24:33.600 ERROR (MainThread) [homeassistant.config_entries] Error migrating entry husqvarna_automower for husqvarna_automower
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 632, in async_migrate
    result = await component.async_migrate_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower/__init__.py", line 171, in async_migrate_entry
    new_options.pop(opt_key)
KeyError: 'enable_camera'
```

**Comment by robinostlund** [comment]
@prairiesnpr nope this is on my test instance where i haven't enabled the camera feature 😄

**Comment by prairiesnpr** [comment]
Thanks, in our testing it didn't show up, I'll make sure we catch it, should be able to get a PR in tonight. Still seems odd, would've expected it to be present in the options.
