### ISSUE TITLE
Integration cannot be restarted from automation

### ISSUE THREAD

**Issue by Din-BH** [Thomas55555/husqvarna_automower#525]
**Describe the bug**
Trying to make the integration restart via automation to revive it when it has lost connection to the MOwer and is left with stale data. The restart fails.

Integration version is 2023.7.0

Command used is:
service: homeassistant.reload_config_entry
data: {}
target:
  entity_id: vacuum.am405x

Log:
Logger: homeassistant.config_entries
Source: custom_components/husqvarna_automower/__init__.py:107
Integration: Husqvarna Automower ([documentation](https://github.com/Thomas55555/husqvarna_automower), [issues](https://github.com/Thomas55555/husqvarna_automower/issues))
First occurred: 11:00:00 (1 occurrences)
Last logged: 11:00:00

Error unloading entry husqvarna_automower for husqvarna_automower
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1155, in _create_direct_connection
    hosts = await asyncio.shield(host_resolved)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 874, in _resolve_host
    addrs = await self._resolver.resolve(host, port, family=self._family)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/resolver.py", line 33, in resolve
    infos = await self._loop.getaddrinfo(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 867, in getaddrinfo
    return await self.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/socket.py", line 962, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
socket.gaierror: [Errno -3] Try again

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 546, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower/__init__.py", line 107, in async_unload_entry
    await coordinator.session.close()
  File "/usr/local/lib/python3.11/site-packages/aioautomower/session.py", line 153, in close
    await asyncio.gather(*tasks)
  File "/usr/local/lib/python3.11/site-packages/aioautomower/session.py", line 336, in _rest_task
    self.data = await self.get_status()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioautomower/session.py", line 168, in get_status
    return await d.async_mower_state()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioautomower/rest.py", line 162, in async_mower_state
    async with session.get(MOWER_API_BASE_URL) as resp:
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 1141, in __aenter__
    self._resp = await self._coro
                 ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client.py", line 536, in _request
    conn = await self._connector.connect(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 540, in connect
    proto = await self._create_connection(req, traces, timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 901, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aiohttp/connector.py", line 1169, in _create_direct_connection
    raise ClientConnectorError(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host api.amc.husqvarna.dev:443 ssl:default [Try again]

**Comment by Din-BH** [comment]
Brilliant.. When I tried a manual restart of the whole HA platform after this, the invalid credentials bug #426 appeared...
