### ISSUE TITLE
Integration won’t load. 

### ISSUE THREAD

**Issue by pguich** [Thomas55555/husqvarna_automower#526]
I tried deleting it from HACS store and redownloading, i tried to delete the integration (won’t work), I restarted HA multiple times, I deleted the credentionals, but I can’t get the integration loaded.

This is the error message:

Logger: homeassistant.setup
Source: custom_components/husqvarna_automower/const.py:3 
Integration: Husqvarna Automower ([documentation](https://github.com/Thomas55555/husqvarna_automower), [issues](https://github.com/Thomas55555/husqvarna_automower/issues)) 
First occurred: 18:46:03 (1 occurrences) 
Last logged: 18:46:03

Setup failed for custom integration husqvarna_automower: Unable to import component: cannot import name 'Polygon' from 'shapely.geometry' (/usr/local/lib/python3.11/site-packages/shapely/geometry/__init__.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 813, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/husqvarna_automower/__init__.py", line 18, in <module>
    from .const import (
  File "/config/custom_components/husqvarna_automower/const.py", line 3, in <module>
    from shapely.geometry import Polygon
ImportError: cannot import name 'Polygon' from 'shapely.geometry' (/usr/local/lib/python3.11/site-packages/shapely/geometry/__init__.py)

**Comment by Thomas55555** [comment]
1. I'll release a beta version the next few minutes. Please try, if it works with that.
2. Are you using docker? The it's probably something similar to this: #519

**Comment by pguich** [comment]
I’m not using docker. I’m running the home assistant OS. I’m about to migrate from an old raspberry pi to a new one and am currently running both in parallel. In the old instance it works fine, in the new one it never worked (I restored from a backup). 
I updated to 2023.8.0b1, but nothing changed. 
i wanted to delete it completely, along with the integration, and then reinstall from scratch, but the integration just won’t go away. 
The only thing I was able to accomplish was deleting the application credentials. 

Thanks so much for your help.

**Comment by Thomas55555** [comment]
What error log do you have now?

**Comment by pguich** [comment]
Actually, the Husqvarna integration is now gone. I’ve removed the download from the HACS store, and downloaded again. But the integration is just not coming back, after several restarts. I can’t manually
 Add the Husqvarna integration either.

**Comment by Thomas55555** [comment]
I've no idea for that.

**Comment by pguich** [comment]
Thanks for trying :). After I downloaded 2023.7 again, I was able to add the integration, and I finally got it to work. I'm not sure what I did differently, but it works.

I really love your integration!

Thanks again for your help!
