### ISSUE TITLE
Wizard does not work

### ISSUE THREAD

**Issue by Rudinskas** [Thomas55555/husqvarna_automower#534]
Could somebody help me with the installation?

From HACS I successfully install husqvarna_automower integration, but cannot add it to the device sector. The wizard does not start.
![Screenshot 2023-08-16 200719](https://github.com/Thomas55555/husqvarna_automower/assets/58530671/6ec77ee1-9416-4a3d-b510-544b4141dc76)

![Screenshot 2023-08-16 200427](https://github.com/Thomas55555/husqvarna_automower/assets/58530671/6093864d-89b4-43c2-b5d7-076ce409e006)

I tried to go into the integration directly, but also where is not working too.
![Screenshot 2023-08-16 200938](https://github.com/Thomas55555/husqvarna_automower/assets/58530671/62a23086-2efa-4aa1-9451-81b6a7f40533)

Does somebody know what did happen to my system? Is possible to integrate it via yaml file?

Thanks!

I'm using:
- Home Assistant 2023.8.2 
- Operating System 10.4

**Comment by prairiesnpr** [comment]
We would need logs to provide any assistance.

**Comment by stefane26** [comment]
Hi, I have the same problem installing the Husqvarna integration.
Here is the error log :


Logger: homeassistant.components.websocket_api.http.connection
Source: helpers/network.py:200
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 14:06:06 (1 occurrences)
Last logged: 14:06:06

[140152143140928] Error handling message: Unknown error (unknown_error) Stéphane from 192.168.10.120 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 331, in handle_integration_list
    "integrations": {
                    ^
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 332, in <dictcomp>
    domain: await _async_integration_config(hass, domain) for domain in domains
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/application_credentials/__init__.py", line 315, in _async_integration_config
    placeholders = await platform.async_get_description_placeholders(hass)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/husqvarna_automower/application_credentials.py", line 23, in async_get_description_placeholders
    "redirect_uri": get_url(hass),
                    ^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/network.py", line 200, in get_url
    raise NoURLAvailableError
homeassistant.helpers.network.NoURLAvailableErrorg
``
Thanks for your help.
Stephane

**Comment by prairiesnpr** [comment]
I think this is a configuration issue, please check the value of Settings - System - Network - Home Assistant Url and make sure it's set.

**Comment by stefane26** [comment]
Thanks prairienpr
That's where the problem came from.
