### ISSUE TITLE
Error 505

### ISSUE THREAD

**Issue by Fiordianto** [Thomas55555/husqvarna_automower#571]
hi, 
after connecting home assistant and automower it doesn't allow me to configure the device and gives me the error "500 Internal Server Error Server got itself in trouble"

**Comment by Werewolfke** [comment]
same here! :(

**Comment by prairiesnpr** [comment]
There are no details provided in this issue report, please fill out the template and provide appropriate logs, that's the only way anyone will be able to provide assistance

**Comment by Fiordianto** [comment]
**Prerequirements**
[ X ] I have connected my mower(s) to the Automower Connect App
[ X ] I have connected my Husqvanra developers account to the Authentication API
[ X ] I have connected my Husqvarna developers account to the Automower Connect API

**Describe the bug**
after I have connected my Husqwarna developers account to Home Assistant, when I try to configure the new device, raises a new error "500 Internal Server Error Server got itself in trouble" and I can't continue to configure my device.

**Screenshots**
<img width="701" alt="Screenshot 2024-02-10 alle 17 29 19" src="https://github.com/Thomas55555/husqvarna_automower/assets/126582541/5c82e65b-6be8-4b1b-9ec8-88e0a72a91e2">
<img width="535" alt="Screenshot 2024-02-10 alle 17 29 54" src="https://github.com/Thomas55555/husqvarna_automower/assets/126582541/cdde517b-e402-4741-824e-946d6dde4f2e">

**Comment by Fiordianto** [comment]
2024-02-10 17:46:28.680 INFO (MainThread) [custom_components.husqvarna_automower.config_flow] Successfully authenticated
2024-02-10 17:46:28.685 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for binary_sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/binary_sensor/__init__.py", line 244, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.696 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for calendar
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/calendar/__init__.py", line 331, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.707 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for image
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/image/__init__.py", line 128, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.717 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for device_tracker
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/device_tracker/config_entry.py", line 81, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.727 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for number
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 125, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.737 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/select/__init__.py", line 115, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.746 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 147, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!
2024-02-10 17:46:28.757 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry husqvarna_automower for vacuum
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 561, in async_unload
    result = await component.async_unload_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py", line 230, in async_unload_entry
    return await component.async_unload_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 203, in async_unload_entry
    raise ValueError("Config entry was never loaded!")
ValueError: Config entry was never loaded!

these are the logs I get after trying to reauthenticate

**Comment by dawiinci** [comment]
Same here. In my case it correlates with the update of Python 3.12.

**Comment by dawiinci** [comment]
I need to reauthenticate each time I update/reinstall HA.

**Comment by dawiinci** [comment]
It asks to reauthenticate everytime after HA restarts. I don't have to update it.
