### ISSUE TITLE
Authentication issues on setup

### ISSUE THREAD

**Issue by gribber** [Thomas55555/husqvarna_automower#67]
Using 2021.5.2 installed via HACS
HA: 2021.5.4 (supervised)

Setup of the integration fails with:
"Unknown error occurred"

Verified username/password and appkey, also tried to renew it

Logs showing:
```
2021-05-20 09:35:52 DEBUG (MainThread) [custom_components.husqvarna_automower.config_flow] Show the setup form to the user
2021-05-20 09:36:28 DEBUG (MainThread) [aioautomower] Resp.status: 200
2021-05-20 09:36:29 DEBUG (MainThread) [aioautomower] Resp.status mower data: 403
2021-05-20 09:36:29 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/config/custom_components/husqvarna_automower/config_flow.py", line 72, in async_step_user
    mower_data = await get_mower_data.async_mower_state()
  File "/usr/local/lib/python3.8/site-packages/aioautomower/__init__.py", line 154, in async_mower_state
    resp.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 1000, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('https://api.amc.husqvarna.dev/v1/mowers/')
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 71, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 135, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 63, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 109, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 199, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 257, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/husqvarna_automower/config_flow.py", line 74, in async_step_user
    except (ClientConnectorError, ClientError):
NameError: name 'ClientError' is not defined
```

**Comment by sirotkaslo** [comment]
Doesn't work for me also, I get the same error: Error handling request.

**Comment by Thomas55555** [comment]
That sounds for me, like you are not connected to the Automower API, see #8 
Are your sure, that you connected this on the husqvarna page?

**Comment by Thomas55555** [comment]
Can you upgrade to version 2021.5.3 before you completely connect to the API, to see, if there is a proper description now? I think there was a change somewhere, and if the API is not fully connected it's now showing a ClientResponseError instead of a ClientError.

**Comment by sirotkaslo** [comment]
Hi,
thank you for your help, it was my mistake, I only connected the authentication API, once I added the automower connect API it started working after a few minutes.

**Comment by gribber** [comment]
You are correct, it was a user failure :-)
After update, as expected, it now shows:
```
Make sure that the Authentication API and the Automower-Connect API is connected with your API-Key: https://developer.husqvarnagroup.cloud/
```

Thanks
