### ISSUE TITLE
Integration does not start correctly

### ISSUE THREAD

**Issue by keylogicjohan** [Thomas55555/husqvarna_automower#74]
I get the following error but I cant understand whats wrong

> husqvarna_automower
Version: 2021.5.3
This is a custom integration!
If you have any issues with this you need to open an issue here:
https://github.com/Thomas55555/husqvarna_automower
-------------------------------------------------------------------

> 2021-06-14 20:30:07 INFO (MainThread) [custom_components.husqvarna_automower] Inizialising UpdateCoordiantor
2021-06-14 20:30:07 DEBUG (MainThread) [custom_components.husqvarna_automower] Updating mower data
2021-06-14 20:30:07 DEBUG (MainThread) [custom_components.husqvarna_automower] Validating the token
2021-06-14 20:30:09 DEBUG (MainThread) [aioautomower] Resp.status validate token: 200
2021-06-14 20:30:10 DEBUG (MainThread) [aioautomower] Resp.status mower data: 200
2021-06-14 20:30:10 DEBUG (MainThread) [custom_components.husqvarna_automower] Mower data: {'data': [{'type': 'mower', 'id': 'xxxxxxxx-xxxxx-xxxxx-xxxxx-xxxxxxxx', 'attributes': {'system': {'name': 'Matilda', 'model': 'Automower 315X', 'serialNumber': xxxxxxxx}, 'battery': {'batteryPercent': 100}, 'mower': {'mode': 'MAIN_AREA', 'activity': 'LEAVING', 'state': 'IN_OPERATION', 'errorCode': 0, 'errorCodeTimestamp': 0}, 'calendar': {'tasks': [{'start': 360, 'duration': 960, 'monday': True, 'tuesday': True, 'wednesday': True, 'thursday': True, 'friday': True, 'saturday': True, 'sunday': True}]}, 'planner': {'nextStartTimestamp': 0, 'override': {'action': 'NO_SOURCE'}, 'restrictedReason': 'NOT_APPLICABLE'}, 'metadata': {'connected': True, 'statusTimestamp': 1623695317189}}}], 'status': 200}
2021-06-14 20:30:10 DEBUG (MainThread) [custom_components.husqvarna_automower] Finished fetching husqvarna_automower data in 3.548 seconds
2021-06-14 20:30:18 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in async_add_entities
tasks = [
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 369, in <listcomp>
tasks = [
File "/config/custom_components/husqvarna_automower/vacuum.py", line 47, in <genexpr>
HusqvarnaAutomowerEntity(coordinator, idx)
File "/config/custom_components/husqvarna_automower/vacuum.py", line 102, in __init__
self.model = f"{self.model_string_splited[1]} {self.model_string_splited[2]}"
IndexError: list index out of range

**Comment by keylogicjohan** [comment]
No,  I only erased the id and serial number the rest is Ctrl+C, Ctrl+V from home assistants log.

**Comment by Thomas55555** [comment]
Okay. I've released a beat version (2021.6.0b1). Can you try, if this works for you?

**Comment by keylogicjohan** [comment]
Yes I can try it out, a bit busy right now but I can try it in an hour or two

**Comment by keylogicjohan** [comment]
It worked without any errors, and I get a unit and entity under Integrations!
Thanks a lot!
